### PR TITLE
Update Units.json

### PR DESCRIPTION
**Pull request by Penguinplus123**
A simple change to black Panther to make him a little less overpowered.

### CODE REVIEW

**Comment by Penguinplus123** [comment]
I don't know how to make a separate version lol I'm on my phone rn I just made this account to do this
If it seems like it ruins the unit then lmk I'm new to githib and general game dev
I suck at balancing

**Comment by SpacedOutChicken** [comment]
I'm saying no to this one, because having an overpowered Black Panther fits well with the general theme of the mod. This is supposed to be the most powerful nation on Earth, after all. However, I will take some of your suggestions, including making the Black Panther more expensive.

**Comment by Penguinplus123** [comment]
Ok ty!

**Comment by Penguinplus123** [comment]
I see it now, the increase in production is fitting as most early game cities can get to like 10 production pretty early on, and the requirement for sacred mount is also fitting. However, could it be an improvement and be required to be placed on a tile that has a sacred mound spot or something? Sounds more sensical, but I'm a crappy game developer in terms of balancing xd you don't wanna see what I make
Just a suggestion
I get him being op it's just that he was easy to get and it didn't seem fitting for him to be meant for use during the ancient era.

**Pull request closed without merging**
